#!/usr/bin/env sh
make svalboard/trackpoint/left:vial
make svalboard/trackpoint/right:vial
make svalboard/trackball/left:vial
make svalboard/trackball/right:vial
make svalboard/mouse/left:vial
make svalboard/mouse/right:vial
make svalboard/left:vial
make svalboard/right:vial
